# Generated by Django 2.0.3 on 2018-04-14 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_challenges_offline',
            field=models.ManyToManyField(blank=True, related_name='users_offline', to='database.Challenge'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='completed_challenges_online',
            field=models.ManyToManyField(blank=True, related_name='users', to='database.Challenge'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relationship',
            field=models.ManyToManyField(related_name='related_to', through='chat.Relationship', to='chat.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(null=True, on_delete=False, related_name='rooms', to='chat.RoomCategory'),
        ),
        migrations.AddField(
            model_name='room',
            name='challenges',
            field=models.ManyToManyField(related_name='rooms', to='database.Challenge'),
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(related_name='rooms', to='chat.UserProfile'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_person',
            field=models.ForeignKey(on_delete=False, related_name='from_people', to='chat.UserProfile'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_person',
            field=models.ForeignKey(on_delete=False, related_name='to_people', to='chat.UserProfile'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=True, related_name='messages', to='chat.Room'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=False, to='chat.UserProfile'),
        ),
        migrations.AddField(
            model_name='expiredroom',
            name='category',
            field=models.ForeignKey(null=True, on_delete=False, related_name='expired_rooms', to='chat.RoomCategory'),
        ),
        migrations.AddField(
            model_name='expiredroom',
            name='challenges',
            field=models.ManyToManyField(related_name='expired_rooms', to='database.Challenge'),
        ),
        migrations.AddField(
            model_name='expiredroom',
            name='users',
            field=models.ManyToManyField(related_name='expired_rooms', to='chat.UserProfile'),
        ),
    ]
