# Generated by Django 2.0.3 on 2018-04-17 18:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180414_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, related_name='rooms', to='chat.RoomCategory'),
        ),
        migrations.AlterField(
            model_name='room',
            name='challenges',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='database.Challenge'),
        ),
        migrations.AlterField(
            model_name='room',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 18, 17, 56, 204692, tzinfo=utc)),
        ),
    ]
