# Generated by Django 2.0.3 on 2018-04-14 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='challenge_name', max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('edit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date edited')),
                ('description', models.CharField(max_length=500)),
                ('popularity', models.PositiveSmallIntegerField(default=0)),
                ('cost', models.PositiveSmallIntegerField(default=100)),
                ('difficulty', models.PositiveSmallIntegerField(default=100)),
                ('category_challenge', models.ManyToManyField(blank=True, related_name='challenge_category', to='database.CategoryChallenge')),
                ('challenge_creator', models.ForeignKey(on_delete=False, to='chat.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PlotChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('challenge_creator', models.ForeignKey(on_delete=False, to='chat.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='plot_challenge',
            field=models.ManyToManyField(blank=True, related_name='plot_challenge', to='database.PlotChallenge'),
        ),
    ]
