# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 16:47
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('edit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date edited')),
                ('description', models.CharField(max_length=500)),
                ('popularity', models.PositiveSmallIntegerField(default=0)),
                ('cost', models.PositiveSmallIntegerField(default=100)),
                ('difficulty', models.PositiveSmallIntegerField(default=100)),
                ('category_challenge', models.ManyToManyField(related_name='challenge_category', to='database.CategoryChallenge')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_banned', models.BooleanField(default=False)),
                ('popularity', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PlotChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('challenge_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Person')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Person'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='plot_challenge',
            field=models.ManyToManyField(related_name='plot_challenge', to='database.PlotChallenge'),
        ),
    ]
