# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='name',
            field=models.CharField(default='challenge_name', max_length=200),
        ),
    ]
